config/routes.rb
Rails.application.routes.draw do

  root to: "general#index"
  get "/modes", to: "general#modes"
  get "/auth/:provider/callback", to: "general#omniauth_callback", as: :omniauth_callback
  get "/logout", to: "general#logout"

    get "/simple", to: "simple#index"
    get "/simple/logging", to: "simple#logging"
    post "/simple/create", to: "simple#create"
    post "/simple/query", to: "simple#query"
    get "/advanced", to: "advanced#index"
    get "/contest", to: "contest#index"
    get "/sota", to: "sota#index"
    get "/current_utc", to: "helper#get_current_utc"
end

app/models/regular_log_entry.rb
class RegularLogEntry < ActiveRecord::Base
    validates :remote_user_id, presence: true
    validates :to_callsign, presence: true, format: { with: /\A[A-Z]{2}[0-9]+[A-Z]+\z/ }
    validates :rst_from, format: { with: /\A[1-5][0-9]?[1-9]?\z/, allow_blank: true }
    validates :rst_to, format: { with: /\A[1-5][0-9]?[1-9]?\z/, allow_blank: true }
    validates :qth_locator, format: { with: /\A[A-Z]{2}[0-9]{2}[a-z]{2}\z/, allow_blank: true }
    validates :mod, inclusion: { in: %w(FM AM CW SSB), allow_blank: true }
    validates :qsl, presence: true, inclusion: { in: %w(yes no impossible) }

    belongs_to :remote_user

    default_scope { order(utc: :desc) }
    scope :for_callsign, ->(q) { where(to_callsign: q.to_s.upcase)}
    scope :from_utc, ->(q) { where("utc >= '#{q}''")}
    scope :to_utc, ->(q) { where("utc <= '#{q}'")}
end

app/models/remote_session.rb
class RemoteSession < ActiveRecord::Base

    belongs_to :remote_user
end

app/models/remote_user.rb
class RemoteUser < ActiveRecord::Base
    validates :callsign, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true

    scope :like, -> (q) { where("UPPER(callsign) LIKE UPPER('%#{q}%')") }

    has_many :remote_sessions
    has_many :regular_log_entries
end

app/controllers/advanced_controller.rb
class AdvancedController < ApplicationController
    def index
    end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :find_user
  before_filter :user_only

  include ApplicationHelper

  protected

  def find_user
        if session['remote_session_token'] != nil
            @session = RemoteSession.find_by_token(session['remote_session_token'])
            if !@session.nil?
                @user = @session.remote_user
                @check = JSON.parse(HTTParty.get("https://rlauth.phitherek.me/api/user_data?access_token=#{@session.token}").body || "{}")
                if @check.include?("status") && @check["status"] == "failure"
                    session['remote_session_token'] = nil
                    redirect_to '/auth/rlauth' and return
                elsif @check.include?("user")
                    @user = RemoteUser.find_by_callsign(@check["user"]["callsign"])
                    if !@user.nil?
                        session['remote_session_token'] = @session.token
                    else
                        session['remote_session_token'] = nil
                    end
                end
            else
                @user = nil
            end
        else
            @user = nil
        end
    end

    def user_only
        redirect_to root_path unless !@user.nil?
    end
end

app/controllers/contest_controller.rb
class ContestController < ApplicationController
    def index
    end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController

    skip_before_filter :user_only, only: [:index, :omniauth_callback]

    def index
        unless @user.nil?
            redirect_to modes_path
        end
    end

    def modes

    end

    def omniauth_callback
        if !auth_hash.nil?
            @user = RemoteUser.find_by_callsign(auth_hash.info.callsign)
            if @user.nil?
                @user = RemoteUser.create(callsign: auth_hash.info.callsign, email: auth_hash.info.email)
                @user.reload
            end
            @session = RemoteSession.new
            @session.token = auth_hash.credentials.token
            @session.token_expires = Time.at(auth_hash.credentials.expires_at)
            @session.refresh_token = auth_hash.credentials.refresh_token
            @session.remote_user = @user
            @session.save!
            @user.save!
            session['remote_session_token'] = @session.token
        end
        redirect_to root_path
    end

    def logout
        HTTParty.post("https://rlauth.phitherek.me/oauth/revoke?token=#{@session.token}")
        @session.destroy
        session.delete('remote_session_token')
        redirect_to root_path
    end

    private

    def auth_hash
        request.env['omniauth.auth']
    end
end

app/controllers/helper_controller.rb
class HelperController < ApplicationController
    def get_current_utc
        time = Time.now.utc
        sdate = time.to_date
        sftime = format_time(time)
        render json: { utc: {time: time.to_s, date: sdate.to_s, ftime: sftime.to_s} }
    end
end

app/controllers/simple_controller.rb
require 'date'

class SimpleController < ApplicationController
    def index
        @entries = @user.regular_log_entries
    end

    def logging
        @entries = @user.regular_log_entries.limit(20)
        @new_entry = RegularLogEntry.new
    end

    def create
        params[:regular_log_entry][:remote_user_id] = @user.id
        params[:regular_log_entry][:mode] = "simple"
        utc = DateTime.parse(params[:utc_date] + " " + params[:utc_time])
        params[:regular_log_entry][:utc] = utc
        @to_user = RemoteUser.find_by_callsign(params[:regular_log_entry][:to_callsign])
        if @to_user.nil?
            params[:regular_log_entry][:qsl] = "impossible"
        else
            @other_entry = @to_user.regular_log_entries.for_callsign(@user.callsign).from_utc(utc-5.minutes).to_utc(utc+5.minutes).first
            if @other_entry != nil
                if @other_entry.rst_from == params[:regular_log_entry][:rst_to] && @other_entry.rst_to == params[:regular_log_entry][:rst_from]
                    params[:regular_log_entry][:qsl] = "yes"
                    @other_entry.qsl = "yes"
                    @other_entry.save!
                else
                    params[:regular_log_entry][:qsl] = "no"
                end
            else
                params[:regular_log_entry][:qsl] = "no"
            end
        end
        @entry = RegularLogEntry.create(entry_params)
        if @entry.new_record?
            flash[:error] = t("flashes.errors.entry_create") + " " + @entry.errors.full_messages.join(", ")
        else
            flash[:success] = t("flashes.successes.entry_create")
            @entries = @user.regular_log_entries.limit(20)
        end
    end

    def query
    end

    private

    def entry_params
        params.require(:regular_log_entry).permit(:to_callsign, :rst_from, :rst_to, :name, :qth, :utc, :remote_user_id, :mode, :qsl)
    end
end

app/controllers/sota_controller.rb
class SotaController < ApplicationController
    def index
    end
end

app/helpers/advanced_helper.rb
module AdvancedHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_time(time)
        time.strftime("%T")
    end
end

app/helpers/contest_helper.rb
module ContestHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/helper_helper.rb
module HelperHelper
end

app/helpers/simple_helper.rb
module SimpleHelper
end

app/helpers/sota_helper.rb
module SotaHelper
end

app/views/advanced/index.html.haml
%h2= t(:under_construction)
%p= t(:available_soon)
= link_to t(:back), modes_path

app/views/application/_flashes.html.haml
- if flash[:success]
  .flash.success
    = flash[:success]
- if flash[:notice]
  .flash.notice
    = flash[:notice]
- if flash[:error]
  .flash.error
    = flash[:error]

app/views/contest/index.html.haml
%h2= t(:under_construction)
%p= t(:available_soon)
= link_to t(:back), modes_path

app/views/general/index.html.haml
%h2= t(".login_required")
%p
  = link_to t(:login), "/auth/rlauth"

app/views/general/modes.html.haml
%h2= t(".select_mode")

%ul
  %li
    = link_to t(".simple"), simple_path
    = t(".simple_description")
  %li
    = link_to t(".advanced"), advanced_path
    = t(".advanced_description")
  %li
    = link_to t(".contest"), contest_path
    = t(".contest_description")
  %li
    = link_to t(".sota"), sota_path
    = t(".sota_description")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RadioLog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      %h1 RadioLog
      %p= t(:subtitle)
      .flashes
        = render partial: "application/flashes", locals: {flash: flash}
    .userbox
      - if @user.nil?
        %p= t(:not_logged_in)
        = link_to t(:login), "/auth/rlauth"
      - else
        %p= t(:logged_in_as, callsign: @user.callsign)
        = link_to t(:logout), logout_path
    .main
      = yield
    %footer
      %p.created_by= t(:created_by)
      %p.radiolog
        = t(:radiolog_tools) + ":"
        = link_to "RLAuth", "https://rlauth.phitherek.me"
        |
        = link_to "RLQTH", "https://rlqth.phitherek.me"
        |
        = link_to "RLCallsign", "https://rlcallsign.phitherek.me"

app/views/simple/_simple_table.html.haml
%table.simple_table
  %thead
    %tr
      %th= t(".to_callsign")
      %th= t(".rst_to")
      %th= t(".rst_from")
      %th= t(".name")
      %th= t(".qth")
      %th= t(".utc_date")
      %th= t(".utc_time")
      %th= t(".qsl")
  %tbody
    - @entries.each do |entry|
      %tr
        %td= entry.to_callsign
        %td= entry.rst_to
        %td= entry.rst_from
        %td= entry.name
        %td= entry.qth
        %td= entry.utc.to_date
        %td= format_time(entry.utc)
        %td= t("qsl." + entry.qsl.to_s)

app/views/simple/create.js.erb
$(".flashes").html("<%= escape_javascript(render({partial: "application/flashes", locals: {flash: flash}})) %>");
<% if !@entry.new_record? %>
    $(".last_log_entries").html("<%= escape_javascript(render({partial: "simple/simple_table"})) %>");
    $(".logging form input[type=text]").val("");
    $(".logging form textarea").val("");
    $("#auto_utc").prop("checked", true);
    $("#auto_utc").change();
    $(".logging form input[type=text]").first().focus();
<% end %>

app/views/simple/index.html.haml
%h2= t(".simple_mode")
%h3= t(".your_log")
- if @entries.empty?
  %p.empty= t(".empty")
- else
  = render partial: "simple_table"
= link_to t(".start_logging"), simple_logging_path
= link_to t(:back), modes_path

app/views/simple/logging.html.haml
%h2= t(".simple_mode")
%h3= t(".logging")
.logging
  = form_for @new_entry, url: simple_create_path, remote: true do |f|
    .row
      = f.label :to_callsign
      = f.text_field :to_callsign
      = f.label :rst_to
      = f.text_field :rst_to
      = f.label :rst_from
      = f.text_field :rst_from
      = f.label :name
      = f.text_field :name
      = f.label :qth
      = f.text_field :qth
      = label_tag :utc_date, t(:utc_date)
      = date_field_tag :utc_date, Time.now.utc.to_date
      = label_tag :utc_time, t(:utc_time)
      = time_field_tag :utc_time, format_time(Time.now.utc)
      = check_box_tag :auto_utc, 1, checked: true
      = label_tag :auto_utc, t(:auto_utc)
    .row
      = f.label :notes
    .row
      = f.text_area :notes, rows: 10, cols: 30
    .row
      = f.submit t(:submit_qso)
%h3= t(".last_log_entries")
.last_log_entries
  - if @entries.empty?
    %p.empty= t(".empty")
  - else
    = render partial: "simple_table"
= link_to t(:back), simple_path

app/views/sota/index.html.haml
%h2= t(:under_construction)
%p= t(:available_soon)
= link_to t(:back), modes_path